.db $0d
.db  >10, <10,'CLEAR0;L=2;*N.',$0d
.db  >20, <20,'P.$30',$22,'         '
.db     $6a,$65,$74,$80,$73,$65,$74,$80,$6d,$69,$6e,$65,$72,$22
.db     $27,$0d
.db  >30, <30,'P.',$27,$0d
.db  >40, <40,'P.',$22,'    ORIGINAL BY TOM WALKER',$22,$27,$0d
.db  >50, <50,'P.',$22,' ATOM VERSION BY KEES VAN OSS',$22,$27,$0d
.db  >60, <60,'P.',$27,$0d
.db  >70, <70,'P.',$22,' COLLECT KEYS, AVOID WORMS AND',$22,$27,$0d
.db  >80, <80,'P.',$22,'SPIKES AT ALL COSTS!! AND WATCH',$22,$27,$0d
.db  >90, <90,'P.',$22,'THAT EVER DECREASING TIME LIMIT',$22,$27,$0d
.db >100,<100,'P.',$27,$0d
.db >110,<110,'P.',$22,'             KEYS :',$22,$27,$0d
.db >120,<120,'P.',$22,'            Z - LEFT',$22,$27,$0d
.db >130,<130,'P.',$22,'            X - RIGHT',$22,$27,$0d
.db >140,<140,'P.',$22,'        SHIFT - JUMP',$22,$27,$27,$0d
.db >150,<150,'P.',$22,'     PRESS SPACE TO START',$22,$0d
.db >160,<160,'LI.#FFE3;LI.#2AC0',$0d
.db $ff
